# Generated by Django 4.0.3 on 2022-04-06 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PROPERTYMANAGEMENT', '0002_tenant_houseallocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AmountToBePaid', models.IntegerField()),
                ('AmountPaid', models.IntegerField()),
                ('Status', models.BooleanField()),
                ('Date', models.CharField(default='04', max_length=7)),
                ('HouseNumber', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PROPERTYMANAGEMENT.houseallocation')),
                ('TenantId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='PaymentTenantId', to='PROPERTYMANAGEMENT.tenant')),
                ('TenantName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='PaymentTenantName', to='PROPERTYMANAGEMENT.tenant')),
            ],
        ),
    ]
