# Generated by Django 4.0.3 on 2022-04-06 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PROPERTYMANAGEMENT', '0003_payments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='TenantId',
            field=models.ForeignKey(db_column='TenantId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='PaymentTenantId', to='PROPERTYMANAGEMENT.tenant'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='TenantName',
            field=models.ForeignKey(db_column='TenantName', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='PaymentTenantName', to='PROPERTYMANAGEMENT.tenant'),
        ),
    ]
