# Generated by Django 4.0.3 on 2022-04-06 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PROPERTYMANAGEMENT', '0006_alter_payments_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payments',
            old_name='HouseNumber',
            new_name='AccountNumber',
        ),
        migrations.RemoveField(
            model_name='payments',
            name='Status',
        ),
    ]
